[2024-09-02T02:09:57.359+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T02:09:54.103190+00:00 [queued]>
[2024-09-02T02:09:57.362+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T02:09:54.103190+00:00 [queued]>
[2024-09-02T02:09:57.362+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-09-02T02:09:57.368+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): data_from_clickhouse> on 2024-09-02 02:09:54.103190+00:00
[2024-09-02T02:09:57.371+0000] {standard_task_runner.py:60} INFO - Started process 1594 to run task
[2024-09-02T02:09:57.374+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_to_sqlite', 'data_from_clickhouse', 'manual__2024-09-02T02:09:54.103190+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse_to_sqlite.py', '--cfg-path', '/tmp/tmp7ecct23q']
[2024-09-02T02:09:57.375+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask data_from_clickhouse
[2024-09-02T02:09:57.418+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T02:09:54.103190+00:00 [running]> on host 49db2d0c7729
[2024-09-02T02:09:57.448+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_to_sqlite' AIRFLOW_CTX_TASK_ID='data_from_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T02:09:54.103190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T02:09:54.103190+00:00'
[2024-09-02T02:10:00.766+0000] {logging_mixin.py:188} INFO - /opt/airflow/data
[2024-09-02T02:10:00.768+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clickhouse_to_sqlite.py", line 31, in data_from_clickhouse
    with open(DATA_PATH.joinpath('Question_1.sql'), 'r') as sql_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/Question_1.sql'
[2024-09-02T02:10:00.782+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_to_sqlite, task_id=data_from_clickhouse, execution_date=20240902T020954, start_date=20240902T020957, end_date=20240902T021000
[2024-09-02T02:10:00.794+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task data_from_clickhouse ([Errno 2] No such file or directory: '/opt/airflow/data/Question_1.sql'; 1594)
[2024-09-02T02:10:00.843+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-02T02:10:00.856+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
