[2024-09-02T00:57:25.176+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:57:22.819869+00:00 [queued]>
[2024-09-02T00:57:25.180+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:57:22.819869+00:00 [queued]>
[2024-09-02T00:57:25.180+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-09-02T00:57:25.189+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): data_from_clickhouse> on 2024-09-02 00:57:22.819869+00:00
[2024-09-02T00:57:25.199+0000] {standard_task_runner.py:60} INFO - Started process 234 to run task
[2024-09-02T00:57:25.205+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_to_sqlite', 'data_from_clickhouse', 'manual__2024-09-02T00:57:22.819869+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse_to_sqlite.py', '--cfg-path', '/tmp/tmprnqe0_ca']
[2024-09-02T00:57:25.208+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask data_from_clickhouse
[2024-09-02T00:57:25.269+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:57:22.819869+00:00 [running]> on host 49db2d0c7729
[2024-09-02T00:57:25.319+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_to_sqlite' AIRFLOW_CTX_TASK_ID='data_from_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:57:22.819869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T00:57:22.819869+00:00'
[2024-09-02T00:57:28.439+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clickhouse_to_sqlite.py", line 33, in data_from_clickhouse
    data = client.query(query).result_rows
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 209, in query
    return self._query_with_context(query_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 225, in _query_with_context
    response = self._raw_request(body,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 454, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 377, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 137 (end of query) (line 6, col 16): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.5.6.45 (official build))

[2024-09-02T00:57:28.484+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_to_sqlite, task_id=data_from_clickhouse, execution_date=20240902T005722, start_date=20240902T005725, end_date=20240902T005728
[2024-09-02T00:57:28.501+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task data_from_clickhouse (HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 137 (end of query) (line 6, col 16): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.5.6.45 (official build))
; 234)
[2024-09-02T00:57:28.559+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-02T00:57:28.585+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
