[2024-09-01T23:04:57.286+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-01T23:04:52.105830+00:00 [queued]>
[2024-09-01T23:04:57.326+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-01T23:04:52.105830+00:00 [queued]>
[2024-09-01T23:04:57.327+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-09-01T23:04:57.333+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): data_from_clickhouse> on 2024-09-01 23:04:52.105830+00:00
[2024-09-01T23:04:57.339+0000] {standard_task_runner.py:60} INFO - Started process 1721 to run task
[2024-09-01T23:04:57.342+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_to_sqlite', 'data_from_clickhouse', 'manual__2024-09-01T23:04:52.105830+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse_to_sqlite.py', '--cfg-path', '/tmp/tmpcfivahgs']
[2024-09-01T23:04:57.343+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask data_from_clickhouse
[2024-09-01T23:04:57.362+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-01T23:04:52.105830+00:00 [running]> on host 3ed24ff23853
[2024-09-01T23:04:57.389+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_to_sqlite' AIRFLOW_CTX_TASK_ID='data_from_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T23:04:52.105830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T23:04:52.105830+00:00'
[2024-09-01T23:04:57.992+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clickhouse_to_sqlite.py", line 33, in data_from_clickhouse
    data = client.execute(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 478, in receive_hello
    packet_type = read_varint(self.fin)
  File "clickhouse_driver/varint.pyx", line 62, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver/bufferedreader.pyx", line 240, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
EOFError: Unexpected EOF while reading bytes
[2024-09-01T23:04:58.007+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_to_sqlite, task_id=data_from_clickhouse, execution_date=20240901T230452, start_date=20240901T230457, end_date=20240901T230458
[2024-09-01T23:04:58.022+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task data_from_clickhouse (Unexpected EOF while reading bytes; 1721)
[2024-09-01T23:04:58.050+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-01T23:04:58.062+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
